name: 5 - Issues workflow

on:
  # Events on issues: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issues
  issues:
    types: [opened, unlabeled, reopened]

permissions:
  issues: write

jobs:

  # Call the workflow to add a label and assign to tdupoiron
  label-and-assign:
    uses: ./.github/workflows/wf05-rw-label-and-comment-issue.yml
    with:
      issue_number: ${{ github.event.issue.number }}
      assignee: tdupoiron
      label: learning2023